
---
version: "3.4"
services:
  morphir-elm:
    image: morphir-elm
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - JAVA_VERSION=17
        - SCALA_VERSIONS=2.13.8,3.1.3
        - MILL_LAUNCHER=0.10.7
        - MILL_VERSIONS=0.10.7